declare
    column_exists exception;
    pragma exception_init (column_exists , -01430);
begin
    execute immediate 'ALTER TABLE SUBMISSIONS 
	ADD (SUBMITTER_STATE VARCHAR2(32),
	    SUBMITTER_START_TIMESTAMP TIMESTAMP,
 		SUBMITTER_END_TIMESTAMP TIMESTAMP,
	    SUBMITTER_RETRY_COUNT NUMBER(4, 0) )';
    exception when column_exists then null;
end;
/

ALTER TABLE SUBMISSIONS ADD SUBMITTER_STATE VARCHAR2(32) DEFAULT 'COMPLETED' NOT NULL;
ALTER TABLE SUBMISSIONS MODIFY SUBMITTER_STATE VARCHAR2(32) DEFAULT 'NEW' NOT NULL;

ALTER TABLE SUBMISSIONS ADD SUBMITTER_START_TIMESTAMP TIMESTAMP;
ALTER TABLE SUBMITTER_END_TIMESTAMP TIMESTAMP;
ALTER TABLE SUBMITTER_RETRY_COUNT NUMBER(4, 0);