ALTER TABLE SUBMISSIONS ADD SUBMITTER_STATUS VARCHAR2(32);
ALTER TABLE SUBMISSIONS ADD SUBMITTER_START_TIMESTAMP TIMESTAMP;
ALTER TABLE SUBMISSIONS ADD SUBMITTER_END_TIMESTAMP TIMESTAMP;
ALTER TABLE SUBMISSIONS ADD SUBMITTER_ERROR_COUNT NUMBER(4, 0) DEFAULT 0;
ALTER TABLE SUBMISSIONS ADD SUBMITTER_MULTI_INSTANCE_CTRL NUMBER(4, 0) DEFAULT 0;